### ISSUE TITLE
Tracking Issue: LSTM Support

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/muriscv-nn#23]
Upstream CMSIS-NN recently implemented support for running LSTMs with CMSIS-NN. Here are few task related to that:

- [ ] Fix broken TFLM integration test due to LSTM changes (see #22)
- [ ] Support scalar (unoptimized) versions of LSTM functions
- [ ] Add reference LSTML model to benchmarking flow (does ARM provide one?)
- [ ] Look into optimizing LSTM performance using VEXT and PEXT specific code (low priority)
