### ISSUE TITLE
Tracking Issue: Fix failing unit test after CMSIS-NN Sync

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/muriscv-nn#58]
**Failing scalar tests (on X86):**
- [ ] test_muriscv_nn_grouped_convolve_s8 (Failed)
- [ ] test_muriscv_nn_lstm_unidirectional_s8 (Failed)
- [ ] test_muriscv_nn_convolve_1_x_n_s8 (Subprocess aborted)
- [ ] test_muriscv_nn_fully_connected_s8 (Failed)
- [ ] test_muriscv_nn_max_pool_s16 (Failed)
- [ ] test_muriscv_nn_avgpool_s8 (Failed)
- [ ] test_muriscv_nn_max_pool_s8 (Failed)
- [ ] test_muriscv_nn_convolve_s16 (SEGFAULT)
- [ ] test_muriscv_nn_avgpool_s16 (Failed)
- [ ] test_muriscv_nn_convolve_1x1_s8_fast (Failed)

**Failing vector tests (on Spike):**
- [ ] test_muriscv_nn_grouped_convolve_s8 (Failed)
- [ ] test_muriscv_nn_convolve_s8 (Failed)
- [ ] test_muriscv_nn_lstm_unidirectional_s8 (Failed)
- [ ] test_muriscv_nn_svdf_s8 (Failed)
- [ ] test_muriscv_nn_convolve_1_x_n_s8 (Failed)
- [ ] test_muriscv_nn_fully_connected_s8 (Failed)
- [ ] test_muriscv_nn_max_pool_s16 (Failed)
- [ ] test_muriscv_nn_avgpool_s8 (Failed)
- [ ] test_muriscv_nn_depthwise_conv_s8_opt (Failed)
- [ ] test_muriscv_nn_max_pool_s8 (Failed)
- [ ] test_muriscv_nn_depthwise_conv_3x3_s8 (Failed)
- [ ] test_muriscv_nn_convolve_s16 (Failed)
- [ ] test_muriscv_nn_avgpool_s16 (Failed)
- [ ] test_muriscv_nn_convolve_1x1_s8_fast (Failed)
- [ ] test_muriscv_nn_ds_cnn_l_s8 (Failed)

**Failing packed tests (on Spike):**
- [ ] test_muriscv_nn_grouped_convolve_s8 (Failed)
- [ ] test_muriscv_nn_lstm_unidirectional_s8 (Failed)
- [ ] test_muriscv_nn_convolve_1_x_n_s8 (Failed)
- [ ] test_muriscv_nn_fully_connected_s8 (Failed)
- [ ] test_muriscv_nn_depthwise_conv_fast_s16 (Failed)
- [ ] test_muriscv_nn_max_pool_s16 (Failed)
- [ ] test_muriscv_nn_avgpool_s8 (Failed)
- [ ] test_muriscv_nn_depthwise_conv_s8_opt (Failed)
- [ ] test_muriscv_nn_max_pool_s8 (Failed)
- [ ] test_muriscv_nn_depthwise_conv_3x3_s8 (Failed)
- [ ] test_muriscv_nn_convolve_s16 (Failed)
- [ ] test_muriscv_nn_avgpool_s16 (Failed)
- [ ] test_muriscv_nn_convolve_1x1_s8_fast (Failed)

**Comment by PhilippvK** [comment]
See https://github.com/tum-ei-eda/muriscv-nn/pull/56 for details

**Comment by PhilippvK** [comment]
@ParkerJones567 That will be a lot of work to this these. I hope I can help to figure out some of them (hopefully the bug is just in a support function used by most of the tests...)
