### ISSUE TITLE
Support Zve32x (and further) extensions in CI, test, benchmarks

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/muriscv-nn#61]
The library already supports Zve32x, but the CI/TC/Simulator related scrips are currently mostly RV32GCV only.

An `-i` flag exists in some scripts for enabling embedded vector mode, but this should be made more generic...

**TODOs:**
- [ ] Provide new Toolchains, at least
  - [x] rv32imzve32x
  - [ ] rv32imczve32x
- [ ] Update Unit Tests
- [ ] Update Integration Tests
- [ ] Update CI Workflows
